- name: get Cloudflare IPs
  get_url:
    url: "https://www.cloudflare.com/ips-v{{ item }}"
    dest: "/etc/cloudflare_ip{{ item }}"
  loop: [4, 6]

- name: slurps Cloudflare IPs
  slurp:
    src: "/etc/cloudflare_ip{{ item }}"
  register: cloudflare_ips_files
  loop: [4, 6]

- name: establish complete list of Cloudflare IPs
  set_fact:
    cloudflare_ips: "{{ ((cloudflare_ips_files.results.0.content|b64decode).split() + (cloudflare_ips_files.results.1.content|b64decode).split()) }}"

- name: nginx trust Cloudflare CF-Connecting-IP header
  template:
    src: "cloudflare.conf.j2"
    dest: "/etc/nginx/conf.d/cloudflare.conf"

- name: 443 and 80 are allowed from Cloudflare IPs
  ufw:
    rule: allow
    direction: in
    from_ip: "{{ item.0 }}"
    to_port: "{{ item.1 }}"
  loop: "{{ cloudflare_ips | product([443, 80]) | list }}"

- name: 443 and 80 are disallowed from rest of the world
  ufw:
    delete: yes
    rule: allow
    direction: in
    to_port: "{{ item }}"
  loop: ["443", "80"]
