# Dans sa séquence d'initialisation, UFW fait un truc un peu bête : il règle la
# politique par défaut *avant* d'avoir inséré la règle qui autorise les paquets
# appartenant à des connexions déjà ouvertes.
#
# Résultat, si on met la politique par défaut à DENY, le changement de politique
# se met à bloquer la connexion des disques réseaux, ce qui coupe les connexions
# déjà existantes… et notamment celles aux disques réseau, ce qui fait planter le
# boot.
#
# Du coup, comme workaround, on indique comme politique par défaut ALLOW, mais
# on rajoute à la chaîne qu'UFW utilise comme post-traitement pour les paquets
# entrants une règle qui droppe tout, dans un fichier que UFW charge *après*
# avoir créé la règle qui autorise les paquets des connexions ouvertes.
#
# On retrouve donc bien le comportement souhaité, avec l'inconvénient majeur que
# rien de tout cela n'est directement visible dans l'interface de UFW qui
# affiche simplement que la politique par défaut est ALLOW.

- name: ufw default allow not to block nbd
  ufw:
    policy: allow

- name: ufw allow ssh
  ufw:
    rule: allow
    port: "22"

- name: ufw drop all packets in "after rules"
  lineinfile:
    path: /etc/ufw/after{{ item }}.rules
    line: "-A ufw{{ item }}-reject-input -j DROP"
    insertbefore: COMMIT
  with_items:
    - ''
    - '6'
